import os
from typing import Optional
import logging
from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

# Configure Gemini API
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "AIzaSyBeG_qYexvLU6xj5xVREQvME-0V1TcaAuI")

# Initialize the client
client = genai.Client(api_key=GEMINI_API_KEY)

# Story generation prompt template
STORY_PROMPT_TEMPLATE = """You are a master storyteller specializing in cultural folklore from around the world.
Create an authentic, engaging folklore story based on the following theme/prompt: "{prompt}"

Guidelines:
- Create a story that feels authentic to traditional oral storytelling
- Include cultural elements, nature imagery, and moral wisdom
- Keep it between 200-400 words
- Use vivid, descriptive language
- Make it suitable for all ages
- Include a subtle moral or lesson

If a specific culture is mentioned, incorporate authentic elements from that tradition.
If the prompt is about a specific topic (animals, nature, moon, etc.), weave it naturally into the story.

Format the story with a title and the story text."""

CHAT_PROMPT_TEMPLATE = """You are FolkloreGPT, an AI assistant specializing in cultural stories, folklore, and myths from indigenous cultures around the world.

User Question: "{query}"
Cultural Context: {culture}
Language: {language}

Respond as a knowledgeable folklore guide:
- If they ask for a specific story and you know one, summarize it beautifully
- If they ask about themes (animals, nature, heroes), suggest relevant stories and briefly describe them
- If they ask about a culture, share interesting folklore facts
- Be respectful of cultural traditions
- Keep responses conversational but informative (150-300 words)
- Suggest related stories or themes they might enjoy

If the query is in a language other than English, respond in that language if possible, or provide translation."""


class GeminiService:
    """Service for generating stories and chat responses using Gemini AI."""

    def __init__(self):
        self.client = client
        self.model = "gemini-2.5-flash"  # Using Gemini 2.5 Flash (2.0 quota was limited)
        self.is_available = True

        # Test the API on init
        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents="Hello",
                config=types.GenerateContentConfig(max_output_tokens=10)
            )
            print("✅ Gemini AI initialized successfully")
        except Exception as e:
            print(f"⚠️ Gemini initialization warning: {e}")
            self.is_available = False

    async def generate_story(self, prompt: str, max_length: int = 400, culture: str = None, tone: str = "traditional") -> dict:
        """Generate a folklore story based on the prompt."""
        try:
            culture_str = f" from {culture} culture" if culture else ""
            tone_str = f" written in a {tone} tone" if tone else ""
            enhanced_prompt = f"{prompt}{culture_str}{tone_str}"
            formatted_prompt = STORY_PROMPT_TEMPLATE.format(prompt=enhanced_prompt)

            response = self.client.models.generate_content(
                model=self.model,
                contents=formatted_prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=max_length * 4,
                    temperature=0.8,
                    top_p=0.9,
                )
            )

            story_text = response.text.strip()

            # Extract title if present
            lines = story_text.split('\n')
            title = "Generated Folktale"
            content = story_text

            for line in lines[:5]:
                if line.strip().lower().startswith('title:'):
                    title = line.split(':', 1)[1].strip()
                elif line.strip() and not title.startswith('Generated'):
                    if not line.strip().startswith('#'):
                        title = line.strip()
                    break

            return {
                "generated_story": story_text,
                "title": title,
                "ai_model_used": True,
                "theme": prompt,
                "note": "Generated by Gemini AI",
                "success": True
            }

        except Exception as e:
            logger.error(f"Error generating story with Gemini: {e}")
            return {
                "generated_story": None,
                "error": str(e),
                "ai_model_used": False,
                "success": False,
                "theme": prompt
            }

    async def chat_response(self, query: str, culture: str = "any", language: str = "english") -> dict:
        """Generate a chat response about folklore."""
        try:
            formatted_prompt = CHAT_PROMPT_TEMPLATE.format(
                query=query,
                culture=culture if culture != "any" else "various cultures",
                language=language
            )

            response = self.client.models.generate_content(
                model=self.model,
                contents=formatted_prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=500,
                    temperature=0.7,
                    top_p=0.9,
                )
            )

            return {
                "response": response.text.strip(),
                "ai_model_used": True,
                "success": True,
                "culture": culture,
                "language": language
            }

        except Exception as e:
            logger.error(f"Error generating chat response with Gemini: {e}")
            return {
                "response": "I apologize, but I'm having trouble accessing my knowledge right now. Please try again.",
                "error": str(e),
                "ai_model_used": False,
                "success": False
            }

    async def analyze_image(self, image_data: bytes, mime_type: str = "image/jpeg") -> dict:
        """Analyze an image and extract text/description using Gemini Vision."""
        try:
            # Upload image to Gemini
            blob = self.client.files.upload(
                file=image_data,
                config={'mime_type': mime_type}
            )

            prompt = """Analyze this image and provide:
1. A description of what's in the image
2. Any text visible in the image (transcribe it)
3. Cultural elements that might be present
4. Suggested story themes based on the image content

Format your response clearly."""

            response = self.client.models.generate_content(
                model=self.model,
                contents=[prompt, blob]
            )

            return {
                "analysis": response.text.strip(),
                "success": True,
                "ai_model_used": True
            }

        except Exception as e:
            logger.error(f"Error analyzing image with Gemini: {e}")
            return {
                "analysis": None,
                "error": str(e),
                "success": False,
                "ai_model_used": False
            }


# Global instance
gemini_service = GeminiService()
